name: Python Automation API Test
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common git
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python3.10-full
          echo "export PATH=/home/seluser/.local/bin:$PATH" >> $GITHUB_ENV
          sudo apt-get install -y python3-pip
          sudo chown -R seluser:seluser /home/seluser/.local/
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install --user pipenv
          pipenv install --python `which python3.10`

      - name: Run tests with pytest
        run: |
          pipenv run pytest test/