name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This workflow was triggered manually!"

#  name: python automation api test
#
#  on:
#    schedule:
#      # Runs at 12 AM UTC every day
#      - cron: '0 0 * * *'
#  jobs:
#    build:
#
#      runs-on: ubuntu-latest
#
#      steps:
#        - uses: actions/checkout@v2
#        - name: Set up Python 3.12
#          uses: actions/setup-python@v2
#          with:
#            python-version: '3.12'
#        - name: Install pipenv and dependencies
#          run: |
#            python -m pip install --upgrade pip
#            pip install pipenv
#            pipenv install --dev
#        - name: Run tests with pytest
#          run: |
#            run: |
#                  pipenv run pytest tests/