name: Python Automation API Test

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Use Python 3.11 to include the exceptiongroup module

      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev # Ensure your Pipfile specifies the required packages

      - name: Run tests with pytest
        run: |
          pipenv run pytest test/
