name: Python Automation API Test
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Change 'x' to the latest minor version available

      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install  --python $(which python)

      - name: Run tests with pytest
        run: |
          pipenv run pytest ./api_approch1/tests/api_test/
