name: Python Automation API Test

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Verify pipenv installation
        run: |
          pip list
          which pipenv
          pipenv --version

      - name: Install dependencies with pipenv
        run: |
          pipenv install --dev

      - name: Run tests with pytest
        run: |
          pipenv run pytest tests/test_api.py
