name: python automation api test

on:
  push:
    branches: [main]
  schedule:
    # Runs at 12 AM UTC every day
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv

      - name: Verify pipenv installation
        run: pipenv --version

      - name: Use pipenv
        run: pipenv --where

      - name: Check Python version
        run: python --version

      - name: Which Python
        run: which python

      - name: Python Version
        run: python --version

      - name: Pipenv --where
        run: pipenv --where

      - name: Pipenv --py
        run: pipenv --py





      - name: Check Pipenv version
        run: pipenv --version

      - name: Install dependencies with Pipenv (Verbose)
        run: pipenv install --dev --verbose

      - name: Run tests with pytest
        run: pipenv run pytest tests/test_api.py